var Reflux = require('reflux');
var React = require('react');

var tasksSchema = [
    "ActualFinish",
    "ActualStart",
    "ActualWorkMinutes",
    "Assignments",
    "CrossProjectPredecessors",
    "Description",
    "DurationMinutes",
    "EtcMinutes",
    "Id",
    "Indent",
    "IsBillable",
    "IsDeliverable",
    "IsMilestone",
    "IsOnCriticalPath",
    "IsParent",
    "Number",
    "OnHold",
    "OutlineNumber",
    "ParentTaskId",
    "PercentComplete",
    "PlannedFinish",
    "PlannedStart",
    "PlannedWorkMinutes",
    "Priority",
    "RelatedItems",
    "SiblingIndex",
    "Status",
    "TaskPredecessorRefs",
    "TaskType",
    "Title",
    "WorkCalendarID"
];


var tasks = {
   schema: tasksSchema,
   tasks: [
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "8a729c8a-5b39-4e1f-87cb-29546b01ccb0",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 15,
        "OnHold": false,
        "OutlineNumber": "13",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1417564800000)/",
        "PlannedStart": "/Date(1417564800000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 983040,
        "Status": 4,
        "TaskPredecessorRefs": [],
        "TaskType": 0,
        "Title": "deskdocs",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 6720,
        "EtcMinutes": 480,
        "Id": "a584d3a0-62fb-4bdb-a476-5c11a4809d69",
        "Indent": 2,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 2,
        "OnHold": false,
        "OutlineNumber": "1.1",
        "ParentTaskId": "92952036-d13a-4850-b224-d1e286b2691b",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1236729600000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 480,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 65536,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issues 2",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "1c00f3db-cecb-4aab-836b-61a1af528f97",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 6,
        "OnHold": false,
        "OutlineNumber": "4",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1235088000000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 393216,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issue 6",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "0ed8dd8b-c9a8-4851-ab7e-7fbdaeb2bc2a",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 7,
        "OnHold": false,
        "OutlineNumber": "5",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1235088000000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 458752,
        "Status": 4,
        "TaskPredecessorRefs": [],
        "TaskType": 0,
        "Title": "Issue 7",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "d8f4e259-5507-44e5-bac9-8d1e72e73127",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 5,
        "OnHold": false,
        "OutlineNumber": "3",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1235088000000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 327680,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issue 5",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "fc63b750-7289-4622-92d5-90cac4f44731",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 9,
        "OnHold": false,
        "OutlineNumber": "7",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1270425600000)/",
        "PlannedStart": "/Date(1270425600000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 589824,
        "Status": 4,
        "TaskType": 2,
        "Title": "Issue 9",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "c0716fd9-c29e-4156-88ae-94be5e2be683",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 12,
        "OnHold": false,
        "OutlineNumber": "10",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1270166400000)/",
        "PlannedStart": "/Date(1270166400000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 786432,
        "Status": 4,
        "TaskType": 0,
        "Title": "sdgfsdg",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "bd413d54-ca40-47f9-833b-9a57ecc545ba",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 14,
        "OnHold": false,
        "OutlineNumber": "12",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1270166400000)/",
        "PlannedStart": "/Date(1270166400000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 917504,
        "Status": 4,
        "TaskPredecessorRefs": [],
        "TaskType": 0,
        "Title": "sdg",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "b1d698e8-042c-4558-9a57-a2a7460fdf14",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 4,
        "OnHold": false,
        "OutlineNumber": "2",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1235088000000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 262144,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issue 4",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "281a23e0-ee7c-4620-9286-a33fed396d81",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 8,
        "OnHold": false,
        "OutlineNumber": "6",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1235088000000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 524288,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issue 8",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 11040,
        "EtcMinutes": 0,
        "Id": "6bdeac7e-0316-4d29-b4fb-a59464d4f197",
        "Indent": 2,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 3,
        "OnHold": false,
        "OutlineNumber": "1.2",
        "ParentTaskId": "92952036-d13a-4850-b224-d1e286b2691b",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1237852800000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 131072,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issue 3",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "770abe3a-2f4f-4ae5-9b82-ca81eddb61e7",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 10,
        "OnHold": false,
        "OutlineNumber": "8",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1242086400000)/",
        "PlannedStart": "/Date(1242086400000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 655360,
        "Status": 4,
        "TaskType": 0,
        "Title": "task type",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 11040,
        "EtcMinutes": 480,
        "Id": "92952036-d13a-4850-b224-d1e286b2691b",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": true,
        "Number": 1,
        "OnHold": false,
        "OutlineNumber": "1",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1237852800000)/",
        "PlannedStart": "/Date(1235088000000)/",
        "PlannedWorkMinutes": 480,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 65536,
        "Status": 4,
        "TaskType": 0,
        "Title": "Issues 1",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "9fcc3cbe-b21a-43ba-8c96-e234b6541617",
        "Indent": 1,
        "IsBillable": true,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 11,
        "OnHold": false,
        "OutlineNumber": "9",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1132272000000)/",
        "PlannedStart": "/Date(1132272000000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 720896,
        "Status": 4,
        "TaskType": 0,
        "Title": "task name",
        "WorkCalendarID": null
    },
    {
        "ActualFinish": null,
        "ActualStart": null,
        "ActualWorkMinutes": 0,
        "Assignments": [],
        "CrossProjectPredecessors": null,
        "Description": "",
        "DurationMinutes": 480,
        "EtcMinutes": 0,
        "Id": "907107aa-cfdd-4a63-8707-fd0d9dd2d4a9",
        "Indent": 1,
        "IsBillable": false,
        "IsDeliverable": false,
        "IsMilestone": false,
        "IsOnCriticalPath": false,
        "IsParent": false,
        "Number": 13,
        "OnHold": false,
        "OutlineNumber": "11",
        "ParentTaskId": "8056f3b0-858e-4ee1-b838-8ec1f99f1c12",
        "PercentComplete": 0,
        "PlannedFinish": "/Date(1270166400000)/",
        "PlannedStart": "/Date(1270166400000)/",
        "PlannedWorkMinutes": 0,
        "Priority": 1,
        "RelatedItems": [],
        "SiblingIndex": 851968,
        "Status": 4,
        "TaskType": 0,
        "Title": "sdgfsdgf",
        "WorkCalendarID": null
    }
    ]
};


var TasksStore = Reflux.createStore({
  getInitialState() {
        return {tasks};
    }
});

module.exports = TasksStore;
